---
title: "Correlation analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(knitr)
```

Loading data for dimension reduction and plotting
```{r loading-data, echo=TRUE, message=FALSE, warning=FALSE}
data<-read_tsv('../data/Train_call.txt')
labels<-read_tsv('../data/Train_clinical.txt')%>%
  rename(sample=Sample,subgroup=Subgroup)
```
Calculating correlations between all regions and between neighbouring regions
```{r}
correlations <- data%>%
  select(-1:-4)%>%
  t()%>%
  cor(method = 'spearman')
  
region_autocorrelation <- 
  data.frame(running_cor = c(NA,correlations[row(correlations)==col(correlations)+1]),
             chr=data$Chromosome,start=data$Start,end=data$End)%>%
  mutate(same_chr=chr==lag(chr))

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
region_autocorrelation%>%
  filter(same_chr)%>%
  ggplot(aes(x=as.factor(chr),y=running_cor,fill=as.factor(chr)))+
  geom_boxplot()+
  labs(title = 'Correlation between neighbouring regions across chromosomes.',
       subtitle = 'Only between regions within the same chromosome.',
       fill='Chromosome',x='Chromosome',
       y='Correlation coefficient')
```
Calculating amount of regions with high correlation
```{r echo=TRUE}
region_metadata <- data%>%
  select(1:3)%>%
  mutate(no = row_number())%>%
  rename(chr=Chromosome,start=Start,end=End)

highly_correlated_regions <- which(correlations>0.5, arr.ind=TRUE)%>%
  as.data.frame()%>%
  filter(col>row)%>%
  mutate(cor = map2_dbl(col,row,~correlations[.x,.y]))%>%
  left_join(region_metadata,by=c('row'='no'))%>%
  left_join(region_metadata,by=c('col'='no'),suffix=c('_1','_2'))

highly_correlated_regions%>%
  arrange(desc(cor))%>%
  write_csv('../data/correlated_regions.csv')

limits = c(0.5,0.6,0.7,0.8,0.9,0.95,1,Inf)
cor_count <- map_dbl(1:(length(limits)-1),~highly_correlated_regions%>%
                       filter(cor<limits[.x+1],cor>=limits[.x])%>%
                       {c(pull(.,row),pull(.,col))}%>%
                       unique()%>%
                       length())

approx_stats<-data.frame(
  cor_count = cor_count, 
  from = limits%>%head(-1), 
  to = limits%>%tail(-1)
  )

highly_correlated_regions%>%
  arrange(desc(cor))%>%
  write_csv('../data/approximate_correlation_stats.csv')

```
Regions with 100% correlation across whole dataset
```{r}
highly_correlated_regions%>%
  filter(cor==1)%>%
  kable()
```
Amount of regions that have high correlation to at least one region with correlation 
value between two limits
```{r}
approx_stats%>%
  kable()
```

